version: '3'
volumes:
  data:
services:
  web:
    build: .
    container_name: ruby-web
    command: /bin/bash -c "while [ true ]; do sleep 10; done"
    ports: ["3000:3000"]
    expose: ["3000"]
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - db:database_srv
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose: ["5432"]
    container_name: pg
    volumes:
      - data:/var/lib/pg
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=myDb
      - PGDATA=data
    networks:
      - postgres

  pgadmin:
    container_name: pgAdmin
    links:
      - db:database_srv
    image: fenglc/pgadmin4
    volumes:
        - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

